### ISSUE TITLE
Stitching result has something wrong make it looks so bad.

### ISSUE THREAD

**Issue by Yi-Jun-Wang** [tlliao/Single-perspective-warps#2]
I tried to run the project with matlab R2022b in Windows 10 x64.
i changed the line 9 of "addNeedPaths.m" to locate my VLFeat lib, and line 95 of "main.m" to 
    "optimized_V = reshape(V_star, [], 2); clear V_star;"

because vec2mat() is not recommended by matlab, so i change it to reshape according to the document
(https://ww2.mathworks.cn/help/comm/ref/vec2mat.html#d126e86110)

then the program execution result was so weird, and i don't know what's wrong.
![linear-5-50-5-5](https://github.com/tlliao/Single-perspective-warps/assets/72263979/dca3be4b-bbea-466a-8f83-68224031e13a)

**Comment by tlliao** [comment]
You should replace "vec2mat()" with "optimized_V = reshape(V_star,2,[])';" since "V_star" is "[x_1, y_1, x_2, y_2,..., x_n, y_n]^T".

**Comment by Yi-Jun-Wang** [comment]
> You should replace "vec2mat()" with "optimized_V = reshape(V_star,2,[])';" since "V_star" is "[x_1, y_1, x_2, y_2,..., x_n, y_n]^T".

Thank you for replying! I have already figure out this problem.
謝謝！
